### ISSUE TITLE
Expanded generalisability of abstract base class

### ISSUE THREAD

**Issue by aliFrancis** [ESA-PhiLab/eo4ai#3]
Having added SPARCS, it became clear there are several things that could have been generalised into the ABC but were not. Some thoughts about possible changes:

- [x] 1.  Make a .yaml for each dataset called 'bands.yaml' with  dataset_file: band(s). Then, read in as self.dataset_bands or something like that, and use those instead of hardcoding them in self.process.

- [x] 2. Similarly, make a .yaml for each dataset to map classes with mask values. Then no hardcoding is required in the metadata['classes'] creation. Instead, ABC can have self.get_classes which reads from yaml based on dataset type. This will be difficult for Landsat7 Irish because of inconsistent annotations.

- [x] 3. Saturation rejection could be made optional and defaults to False.

- [x] 4. Separate the read function for the mask from the encode. Encode could be generalisable in ABC if done carefully. This will then use the dataset/classes.yaml

- [x] 5. More speculative, SPARCS uses a single .tif for its data. This has two knock-on effects that break the generality of our approach: (a) The nominal resolution is a dataset-defined value, not sensor-defined. (b) All per-band functions need to be converted to loops over all bands. We should decide if (i) the ABC functions will handle both types, mapped lists or full arrays (ii) bands from these single-tif datasets are converted into a list somehow and fed into the existing functions or, (iii) we have an inheritable class for OneBandPerImageDataset vs MultiBandPerImageDataset which has different functions accordingly.

- [x] 6. self.process has turned into a pretty large repetitive function. Perhaps we could break it up and put more of it back into the parent class.

Some other small bugs:

- [x] L7 Irish incorrectly normalises temperatures

- [x] Strides are not used to compute number of steps, meaning full scene is not used when stride<patch_size

**Comment by aliFrancis** [comment]
Worth noting that USGS have been very responsive with regards to the Irish dataset problems. Hopefully they will fix a lot of the issues, especially the inconsistent labelling. Therefore, we shouldn't design for it in the longterm

**Comment by JohnMrziglod** [comment]
These points are all valid, after some discussion here is the the new strategy we may follow:
> Edge cases should be covered by specific dataset class, utilies are for shared functions.

## New structure of Dataset base class:
```
Dataset(ABC):
    def process():
        scenes = self.get_scenes()
        with Pool() as pool:
            pool.map(self.process_scene, scenes)
            
        # dump command line options to README

    @abstractmethod
    def process_scene(self, ...):
        pass
    
    @abstractmethod
    def get_scenes(self, ...):
        pass
```
        
    

## Components / Utilies we will need
- Reader
- Normaliser
- Resizer (scene and mask)
- Mask Encoder
- Splitter
- Saver (one patch)

## Structure of module

prepare_datasets.py
datasets.py (classes)
utils.py (composites)
constants/dataset.yaml
tests/...

**Comment by aliFrancis** [comment]
All 4 datasets now outputting data using new design on branch 'Composition', testing to be done to confirm data is accurate, then PR can be made.

**Comment by aliFrancis** [comment]
Now confident that data is correct and bugs are fixed. Will merge branch and close.
