### ISSUE TITLE
May I contribute to this repo/github organization?

### ISSUE THREAD

**Issue by ucalyptus** [ESA-PhiLab/eo4ai#8]
Here is a small piece of my work in ML based Remote Sensing 
[Link to Project](https://ucalyptus.github.io/EarthEngine-Deep-Learning/index.slides.html)

**Comment by ucalyptus** [comment]
By the way I also code in Pytorch -> https://github.com/ucalyptus/BS-Nets-Implementation-Pytorch

**Comment by aliFrancis** [comment]
Hi Sayantan,

Thanks for getting in touch! Do you have any specific features/aspects of the project that you'd like to work on? Is our readme clear enough in understanding what we are trying to achieve with the project? If not then please ask me about anything you're unsure of.

Thanks
